# import_data.py
import os
from db_manager import init_db, add_words_bulk, get_stats, DB_NAME

# ==========================================
# 完整单词库 (Unit 1 - Unit 12)
# ==========================================
full_vocabulary_data = [
    # --- Unit 1 ---
    ("beach", "an area of sand or rocks next to the sea", "Unit 1"),
    ("cousin", "a child of your uncle or aunt", "Unit 1"),
    ("friend", "someone who you know well and like", "Unit 1"),
    ("holiday", "a time when you do not have to go to work or school", "Unit 1"),
    ("idea", "a plan of action", "Unit 1"),
    ("lemonade", "a drink made usually of lemon juice, sugar, and water", "Unit 1"),
    ("scientist", "someone who studies science or works in science", "Unit 1"),
    ("fair", "of a person's hair, skin, etc., having a light color", "Unit 1"),
    ("shark", "a large and often dangerous sea fish with very sharp teeth", "Unit 1"),
    ("clever", "able to learn and understand things quickly and easily", "Unit 1"),
    ("trick", "something done to surprise or cheat someone", "Unit 1"),
    ("old", "having lived for a long time", "Unit 1"),
    ("beautiful", "very attractive", "Unit 1"),
    ("grey", "having a colour between black and white", "Unit 1"),
    ("funny", "making you smile or laugh", "Unit 1"),
    ("dark", "black or brown in colour", "Unit 1"),
    ("stupid", "silly or not smart", "Unit 1"),
    ("cold", "having a low temperature", "Unit 1"),
    ("house", "a building where people live", "Unit 1"),
    ("hungry", "wanting or needing food", "Unit 1"),
    ("ugly", "unpleasant to look at", "Unit 1"),
    ("sea", "a large area of salt water", "Unit 1"),
    ("young", "having lived for only a short time: not old", "Unit 1"),
    ("warm", "having a temperature between cool and hot", "Unit 1"),
    ("amazing", "very surprising", "Unit 1"),
    ("daughter", "a female child", "Unit 1"),
    ("stay", "to continue to be in a place, job, etc. and not leave", "Unit 1"),
    ("son", "a male child", "Unit 1"),
    ("swimmer", "a person who swims", "Unit 1"),
    ("sister", "a girl or woman who has one or both of the same parents", "Unit 1"),
    ("sometimes", "at times: now and then", "Unit 1"),
    ("brother", "a boy or man who has one or both of the same parents", "Unit 1"),
    ("wife", "a married woman", "Unit 1"),
    ("egg", "a round or oval thing from a female chicken, that you eat as food", "Unit 1"),
    ("husband", "a married man", "Unit 1"),
    ("chick", "a baby bird, especially a baby chicken", "Unit 1"),
    ("uncle", "the brother of your father or mother", "Unit 1"),
    ("twin", "one of two babies that are born at the same time", "Unit 1"),
    ("aunt", "the sister of your father or mother", "Unit 1"),
    ("grandad", "the father of your father or mother", "Unit 1"),
    ("grandma", "the mother of your father or mother", "Unit 1"),
    ("penguin", "a large, black and white sea bird that swims and cannot fly", "Unit 1"),
    ("brown", "having a colour like coffee or chocolate", "Unit 1"),
    ("French", "the people of France", "Unit 1"),
    ("together", "with each other", "Unit 1"),
    ("crazy about", "liking someone or something very much", "Unit 1"),

    # --- Unit 2 ---
    ("computer game", "a game that is played on a computer", "Unit 2"),
    ("laptop", "a small computer to be carried around", "Unit 2"),
    ("lots of", "a large number or amount of", "Unit 2"),
    ("board game", "a game that is played on a board", "Unit 2"),
    ("toy", "something a child plays with", "Unit 2"),
    ("touch", "to put your hand on something", "Unit 2"),
    ("message", "information that one person gives to another", "Unit 2"),
    ("museum", "a building for art, history, or science", "Unit 2"),
    ("strange", "surprising because not usual", "Unit 2"),
    ("puzzle", "a game using skill", "Unit 2"),
    ("skateboard", "a board with wheels on the bottom", "Unit 2"),
    ("lizard", "a small animal with thick skin and a long tail", "Unit 2"),
    ("mobile phone", "a small telephone used outside", "Unit 2"),
    ("robot", "a machine controlled by a computer", "Unit 2"),
    ("bike", "a bicycle", "Unit 2"),
    ("scared", "afraid of something", "Unit 2"),
    ("pet", "an animal that someone keeps in their home", "Unit 2"),
    ("country", "an area of land that has its own government", "Unit 2"),
    ("piece", "an amount of something, or a part of something", "Unit 2"),
    ("exciting", "causing feelings of happiness and interest", "Unit 2"),
    ("mystery", "something that is strange or not known", "Unit 2"),
    ("present", "something that you give to someone as a gift", "Unit 2"),
    ("teddy bear", "a soft toy bear", "Unit 2"),
    ("creepy", "strange or scary", "Unit 2"),
    ("information", "facts or details about somebody/something", "Unit 2"),
    ("dragon", "a big, imaginary animal that can breathe out fire", "Unit 2"),
    ("homework", "work that a student is given to do at home", "Unit 2"),
    ("magic", "having special powers", "Unit 2"),
    ("moon", "the round object that shines in the sky at night", "Unit 2"),
    ("spider", "a small creature that has eight legs", "Unit 2"),
    ("birthday", "the day on which someone was born", "Unit 2"),
    ("move", "to cause to go from one position to another", "Unit 2"),
    ("in", "at a point inside an area or a space", "Unit 2"),
    ("monster", "something that is very large, ugly, and scary", "Unit 2"),
    ("on", "touching and being supported by the surface", "Unit 2"),
    ("next to", "very close to something or someone", "Unit 2"),
    ("favourite", "most liked", "Unit 2"),
    ("under", "at a lower level than something", "Unit 2"),
    ("boring", "not interesting or exciting", "Unit 2"),
    ("guitar", "a musical instrument with strings", "Unit 2"),
    ("near", "close to someone or something", "Unit 2"),
    ("between", "in the space that separates two places", "Unit 2"),
    ("difficult", "not easy", "Unit 2"),
    ("in front of", "directly before or ahead of", "Unit 2"),
    ("fun", "amusing or enjoyable", "Unit 2"),
    ("behind", "at or to the back of someone or something", "Unit 2"),
    ("boat", "a small vehicle used on water", "Unit 2"),
    ("story", "a description of imaginary events", "Unit 2"),
    ("photo", "a picture made by a camera", "Unit 2"),
    ("DVD", "a small disc for storing music or films", "Unit 2"),
    ("fast", "moving, happening, or doing something quickly", "Unit 2"),

    # --- Unit 3 ---
    ("date", "a particular day of a month or year", "Unit 3"),
    ("correct", "true or accurate: having no mistakes", "Unit 3"),
    ("answer", "response to a question", "Unit 3"),
    ("nice", "kind and friendly", "Unit 3"),
    ("sum", "the result of adding numbers", "Unit 3"),
    ("future", "the time that is to come", "Unit 3"),
    ("teacher", "someone whose job is to teach", "Unit 3"),
    ("good luck", "hope for success", "Unit 3"),
    ("calculator", "device used to do maths", "Unit 3"),
    ("maths", "study of numbers and shapes", "Unit 3"),
    ("silence", "state with no sound", "Unit 3"),
    ("history", "study of past events", "Unit 3"),
    ("geography", "study of the world's surface", "Unit 3"),
    ("subject", "area of knowledge studied in school", "Unit 3"),
    ("science", "study of the natural world", "Unit 3"),
    ("clean", "to remove dirt", "Unit 3"),
    ("art", "making paintings or drawings", "Unit 3"),
    ("have fun", "to enjoy oneself", "Unit 3"),
    ("music", "art of pleasant sounds", "Unit 3"),
    ("wear", "to have on your body", "Unit 3"),
    ("sport", "game or activity for health or enjoyment", "Unit 3"),
    ("sing", "make musical sounds with voice", "Unit 3"),
    ("football", "game kicking a round ball", "Unit 3"),
    ("helmet", "hard hat for protection", "Unit 3"),
    ("uniform", "special clothing for a group", "Unit 3"),
    ("playground", "outdoor area for play", "Unit 3"),
    ("carry", "to hold and move something", "Unit 3"),
    ("bookcase", "shelves to hold books", "Unit 3"),
    ("mask", "covering for face", "Unit 3"),
    ("classmate", "member of the same class", "Unit 3"),
    ("brush", "to clean with a brush", "Unit 3"),
    ("cafeteria", "place to get food at school", "Unit 3"),
    ("club", "group for shared activity", "Unit 3"),
    ("library", "place where books are kept", "Unit 3"),
    ("spaghetti", "long thin pasta", "Unit 3"),
    ("pupil", "young person at school", "Unit 3"),
    ("breakfast", "morning meal", "Unit 3"),
    ("often", "many times", "Unit 3"),
    ("travel", "to go on a journey", "Unit 3"),
    ("penfriend", "friend you write to", "Unit 3"),
    ("never", "not ever", "Unit 3"),
    ("email", "electronic messages", "Unit 3"),
    ("always", "every time", "Unit 3"),
    ("usually", "most of the time", "Unit 3"),

    # --- Unit 4 ---
    ("competition", "event to try to win a prize", "Unit 4"),
    ("winner", "one who wins", "Unit 4"),
    ("need", "must have something", "Unit 4"),
    ("congratulations", "words for success", "Unit 4"),
    ("money", "coins or bills to buy things", "Unit 4"),
    ("prize", "reward for winning", "Unit 4"),
    ("fantastic", "very good", "Unit 4"),
    ("collect", "bring things together as hobby", "Unit 4"),
    ("matter", "to be important", "Unit 4"),
    ("go", "move or travel", "Unit 4