# import_data.py
import os
from db_manager import init_db, add_words_bulk, get_stats, DB_NAME

# ==========================================
# 完整单词库 (Unit 1 - Unit 12)
# ==========================================
full_vocabulary_data = [
    # --- Unit 1 ---
    ("beach", "an area of sand or rocks next to the sea", "Unit 1"),
    ("cousin", "a child of your uncle or aunt", "Unit 1"),
    ("friend", "someone who you know well and like", "Unit 1"),
    ("holiday", "a time when you do not have to go to work or school", "Unit 1"),
    ("idea", "a plan of action", "Unit 1"),
    ("lemonade", "a drink made usually of lemon juice, sugar, and water", "Unit 1"),
    ("scientist", "someone who studies science or works in science", "Unit 1"),
    ("fair", "of a person's hair, skin, etc., having a light color", "Unit 1"),
    ("shark", "a large and often dangerous sea fish with very sharp teeth", "Unit 1"),
    ("clever", "able to learn and understand things quickly and easily", "Unit 1"),
    ("trick", "something done to surprise or cheat someone", "Unit 1"),
    ("old", "having lived for a long time", "Unit 1"),
    ("beautiful", "very attractive", "Unit 1"),
    ("grey", "having a colour between black and white", "Unit 1"),
    ("funny", "making you smile or laugh", "Unit 1"),
    ("dark", "black or brown in colour", "Unit 1"),
    ("stupid", "silly or not smart", "Unit 1"),
    ("cold", "having a low temperature", "Unit 1"),
    ("house", "a building where people live", "Unit 1"),
    ("hungry", "wanting or needing food", "Unit 1"),
    ("ugly", "unpleasant to look at", "Unit 1"),
    ("sea", "a large area of salt water", "Unit 1"),
    ("young", "having lived for only a short time: not old", "Unit 1"),
    ("warm", "having a temperature between cool and hot", "Unit 1"),
    ("amazing", "very surprising", "Unit 1"),
    ("daughter", "a female child", "Unit 1"),
    ("stay", "to continue to be in a place, job, etc. and not leave", "Unit 1"),
    ("son", "a male child", "Unit 1"),
    ("swimmer", "a person who swims", "Unit 1"),
    ("sister", "a girl or woman who has one or both of the same parents", "Unit 1"),
    ("sometimes", "at times: now and then", "Unit 1"),
    ("brother", "a boy or man who has one or both of the same parents", "Unit 1"),
    ("wife", "a married woman", "Unit 1"),
    ("egg", "a round or oval thing from a female chicken, that you eat as food", "Unit 1"),
    ("husband", "a married man", "Unit 1"),
    ("chick", "a baby bird, especially a baby chicken", "Unit 1"),
    ("uncle", "the brother of your father or mother", "Unit 1"),
    ("twin", "one of two babies that are born at the same time", "Unit 1"),
    ("aunt", "the sister of your father or mother", "Unit 1"),
    ("grandad", "the father of your father or mother", "Unit 1"),
    ("grandma", "the mother of your father or mother", "Unit 1"),
    ("penguin", "a large, black and white sea bird that swims and cannot fly", "Unit 1"),
    ("brown", "having a colour like coffee or chocolate", "Unit 1"),
    ("French", "the people of France", "Unit 1"),
    ("together", "with each other", "Unit 1"),
    ("crazy about", "liking someone or something very much", "Unit 1"),

    # --- Unit 2 ---
    ("computer game", "a game that is played on a computer", "Unit 2"),
    ("laptop", "a small computer to be carried around", "Unit 2"),
    ("lots of", "a large number or amount of", "Unit 2"),
    ("board game", "a game that is played on a board", "Unit 2"),
    ("toy", "something a child plays with", "Unit 2"),
    ("touch", "to put your hand on something", "Unit 2"),
    ("message", "information that one person gives to another", "Unit 2"),
    ("museum", "a building for art, history, or science", "Unit 2"),
    ("strange", "surprising because not usual", "Unit 2"),
    ("puzzle", "a game using skill", "Unit 2"),
    ("skateboard", "a board with wheels on the bottom", "Unit 2"),
    ("lizard", "a small animal with thick skin and a long tail", "Unit 2"),
    ("mobile phone", "a small telephone used outside", "Unit 2"),
    ("robot", "a machine controlled by a computer", "Unit 2"),
    ("bike", "a bicycle", "Unit 2"),
    ("scared", "afraid of something", "Unit 2"),
    ("pet", "an animal that someone keeps in their home", "Unit 2"),
    ("country", "an area of land that has its own government", "Unit 2"),
    ("piece", "an amount of something, or a part of something", "Unit 2"),
    ("exciting", "causing feelings of happiness and interest", "Unit 2"),
    ("mystery", "something that is strange or not known", "Unit 2"),
    ("present", "something that you give to someone as a gift", "Unit 2"),
    ("teddy bear", "a soft toy bear", "Unit 2"),
    ("creepy", "strange or scary", "Unit 2"),
    ("information", "facts or details about somebody/something", "Unit 2"),
    ("dragon", "a big, imaginary animal that can breathe out fire", "Unit 2"),
    ("homework", "work that a student is given to do at home", "Unit 2"),
    ("magic", "having special powers", "Unit 2"),
    ("moon", "the round object that shines in the sky at night", "Unit 2"),
    ("spider", "a small creature that has eight legs", "Unit 2"),
    ("birthday", "the day on which someone was born", "Unit 2"),
    ("move", "to cause to go from one position to another", "Unit 2"),
    ("in", "at a point inside an area or a space", "Unit 2"),
    ("monster", "something that is very large, ugly, and scary", "Unit 2"),
    ("on", "touching and being supported by the surface", "Unit 2"),
    ("next to", "very close to something or someone", "Unit 2"),
    ("favourite", "most liked", "Unit 2"),
    ("under", "at a lower level than something", "Unit 2"),
    ("boring", "not interesting or exciting", "Unit 2"),
    ("guitar", "a musical instrument with strings", "Unit 2"),
    ("near", "close to someone or something", "Unit 2"),
    ("between", "in the space that separates two places", "Unit 2"),
    ("difficult", "not easy", "Unit 2"),
    ("in front of", "directly before or ahead of", "Unit 2"),
    ("fun", "amusing or enjoyable", "Unit 2"),
    ("behind", "at or to the back of someone or something", "Unit 2"),
    ("boat", "a small vehicle used on water", "Unit 2"),
    ("story", "a description of imaginary events", "Unit 2"),
    ("photo", "a picture made by a camera", "Unit 2"),
    ("DVD", "a small disc for storing music or films", "Unit 2"),
    ("fast", "moving, happening, or doing something quickly", "Unit 2"),

    # --- Unit 3 ---
    ("date", "a particular day of a month or year", "Unit 3"),
    ("correct", "true or accurate: having no mistakes", "Unit 3"),
    ("answer", "response to a question", "Unit 3"),
    ("nice", "kind and friendly", "Unit 3"),
    ("sum", "the result of adding numbers", "Unit 3"),
    ("future", "the time that is to come", "Unit 3"),
    ("teacher", "someone whose job is to teach", "Unit 3"),
    ("good luck", "hope for success", "Unit 3"),
    ("calculator", "device used to do maths", "Unit 3"),
    ("maths", "study of numbers and shapes", "Unit 3"),
    ("silence", "state with no sound", "Unit 3"),
    ("history", "study of past events", "Unit 3"),
    ("geography", "study of the world's surface", "Unit 3"),
    ("subject", "area of knowledge studied in school", "Unit 3"),
    ("science", "study of the natural world", "Unit 3"),
    ("clean", "to remove dirt", "Unit 3"),
    ("art", "making paintings or drawings", "Unit 3"),
    ("have fun", "to enjoy oneself", "Unit 3"),
    ("music", "art of pleasant sounds", "Unit 3"),
    ("wear", "to have on your body", "Unit 3"),
    ("sport", "game or activity for health or enjoyment", "Unit 3"),
    ("sing", "make musical sounds with voice", "Unit 3"),
    ("football", "game kicking a round ball", "Unit 3"),
    ("helmet", "hard hat for protection", "Unit 3"),
    ("uniform", "special clothing for a group", "Unit 3"),
    ("playground", "outdoor area for play", "Unit 3"),
    ("carry", "to hold and move something", "Unit 3"),
    ("bookcase", "shelves to hold books", "Unit 3"),
    ("mask", "covering for face", "Unit 3"),
    ("classmate", "member of the same class", "Unit 3"),
    ("brush", "to clean with a brush", "Unit 3"),
    ("cafeteria", "place to get food at school", "Unit 3"),
    ("club", "group for shared activity", "Unit 3"),
    ("library", "place where books are kept", "Unit 3"),
    ("spaghetti", "long thin pasta", "Unit 3"),
    ("pupil", "young person at school", "Unit 3"),
    ("breakfast", "morning meal", "Unit 3"),
    ("often", "many times", "Unit 3"),
    ("travel", "to go on a journey", "Unit 3"),
    ("penfriend", "friend you write to", "Unit 3"),
    ("never", "not ever", "Unit 3"),
    ("email", "electronic messages", "Unit 3"),
    ("always", "every time", "Unit 3"),
    ("usually", "most of the time", "Unit 3"),

    # --- Unit 4 ---
    ("competition", "event to try to win a prize", "Unit 4"),
    ("winner", "one who wins", "Unit 4"),
    ("need", "must have something", "Unit 4"),
    ("congratulations", "words for success", "Unit 4"),
    ("money", "coins or bills to buy things", "Unit 4"),
    ("prize", "reward for winning", "Unit 4"),
    ("fantastic", "very good", "Unit 4"),
    ("collect", "bring things together as hobby", "Unit 4"),
    ("matter", "to be important", "Unit 4"),
    ("go", "move or travel", "Unit 4"),
    ("kite", "toy that flies on a string", "Unit 4"),
    ("play", "make music with instrument", "Unit 4"),
    ("watch", "look at for a time", "Unit 4"),
    ("huge", "very large", "Unit 4"),
    ("hobby", "activity for pleasure", "Unit 4"),
    ("visitor", "someone who visits", "Unit 4"),
    ("popular", "liked by many", "Unit 4"),
    ("famous", "known by many", "Unit 4"),
    ("amusement park", "place with games and rides", "Unit 4"),
    ("mirror", "glass that reflects", "Unit 4"),
    ("entrance", "opening to enter", "Unit 4"),
    ("view", "things you can see", "Unit 4"),
    ("tourist", "visitor for pleasure", "Unit 4"),
    ("roller coaster", "exciting train ride", "Unit 4"),
    ("ferris wheel", "large turning wheel ride", "Unit 4"),
    ("Internet café", "place to use computers", "Unit 4"),
    ("merry-go-round", "round ride with horses", "Unit 4"),
    ("week", "seven days", "Unit 4"),
    ("sports center", "building for sports", "Unit 4"),
    ("weekend", "Saturday and Sunday", "Unit 4"),
    ("theater", "building to watch plays", "Unit 4"),
    ("summer", "warmest season", "Unit 4"),
    ("meal", "time for eating", "Unit 4"),
    ("restaurant", "place to buy and eat meals", "Unit 4"),
    ("cinema", "place to watch movies", "Unit 4"),
    ("bowling", "game rolling a ball at pins", "Unit 4"),
    ("parent", "father or mother", "Unit 4"),
    ("film", "movie", "Unit 4"),
    ("send", "cause to go somewhere", "Unit 4"),
    ("email address", "destination for email", "Unit 4"),
    ("outside", "not inside", "Unit 4"),
    ("swim", "move through water", "Unit 4"),
    ("free", "not busy", "Unit 4"),
    ("great", "very good", "Unit 4"),

    # --- Unit 5 ---
    ("quiet", "without much noise", "Unit 5"),
    ("throw", "push through air with hand", "Unit 5"),
    ("paint", "colored liquid", "Unit 5"),
    ("fight", "use force to hurt", "Unit 5"),
    ("stall", "table or small shop", "Unit 5"),
    ("ouch", "cry of pain", "Unit 5"),
    ("shot", "act of hitting/kicking ball", "Unit 5"),
    ("loud", "making lot of noise", "Unit 5"),
    ("festival", "series of public events", "Unit 5"),
    ("balloon", "rubber bag with air", "Unit 5"),
    ("invitation", "offer to go somewhere", "Unit 5"),
    ("catch", "hold something thrown", "Unit 5"),
    ("candle", "wax stick for burning", "Unit 5"),
    ("child", "young person", "Unit 5"),
    ("cake", "sweet baked food", "Unit 5"),
    ("adult", "fully grown person", "Unit 5"),
    ("card", "folded paper with message", "Unit 5"),
    ("carnival", "festival with costumes", "Unit 5"),
    ("costume", "clothes to look like someone else", "Unit 5"),
    ("treasure hunt", "game to find hidden prize", "Unit 5"),
    ("parade", "line of people celebrating", "Unit 5"),
    ("clown", "funny person with red nose", "Unit 5"),
    ("secret", "hidden from others", "Unit 5"),
    ("cowboy", "man who rides horse", "Unit 5"),
    ("look for", "try to find", "Unit 5"),
    ("clue", "help to solve puzzle", "Unit 5"),
    ("magician", "person doing magic tricks", "Unit 5"),
    ("burn", "set on fire", "Unit 5"),
    ("model", "small copy of something", "Unit 5"),
    ("firework", "explosive lights for celebration", "Unit 5"),
    ("pirate", "sea robber", "Unit 5"),
    ("preparation", "making ready", "Unit 5"),
    ("witch", "woman with magic power", "Unit 5"),
    ("fire", "heat and flames", "Unit 5"),
    ("joke", "funny story", "Unit 5"),
    ("change", "make different", "Unit 5"),
    ("late", "after expected time", "Unit 5"),
    ("night", "time when dark", "Unit 5"),
    ("laugh", "make sound when happy", "Unit 5"),
    ("test", "questions to check knowledge", "Unit 5"),
    ("barbecue", "cooking outdoors over fire", "Unit 5"),
    ("silver", "shiny grey-white metal", "Unit 5"),
    ("celebrate", "do something special", "Unit 5"),
    ("chocolate", "sweet brown food", "Unit 5"),
    ("watch", "clock on wrist", "Unit 5"),
    ("bring", "take with you", "Unit 5"),
    ("party", "event for fun", "Unit 5"),
    ("invite", "ask someone to come", "Unit 5"),

    # --- Unit 6 ---
    ("fast food", "food served quickly", "Unit 6"),
    ("tomato", "red fruit used as vegetable", "Unit 6"),
    ("over", "in direction of", "Unit 6"),
    ("sandwich", "bread with filling", "Unit 6"),
    ("menu", "list of food", "Unit 6"),
    ("ketchup", "tomato sauce", "Unit 6"),
    ("burger", "meat between bread", "Unit 6"),
    ("juice", "liquid from fruit", "Unit 6"),
    ("chip", "fried potato piece", "Unit 6"),
    ("pill", "small medicine", "Unit 6"),
    ("cheese", "food made from milk", "Unit 6"),
    ("real", "not false", "Unit 6"),
    ("maybe", "possibly", "Unit 6"),
    ("delicious", "tasty", "Unit 6"),
    ("tasty", "good flavor", "Unit 6"),
    ("rubbish", "things thrown away", "Unit 6"),
    ("waiter", "server in restaurant", "Unit 6"),
    ("special", "not usual", "Unit 6"),
    ("chewing gum", "candy you chew", "Unit 6"),
    ("system", "parts working together", "Unit 6"),
    ("long", "taking much time", "Unit 6"),
    ("wait", "stay until something happens", "Unit 6"),
    ("cut", "divide with knife", "Unit 6"),
    ("animal", "living thing not plant", "Unit 6"),
    ("wish", "hope for something", "Unit 6"),
    ("middle", "center part", "Unit 6"),
    ("leaf", "green plant part", "Unit 6"),
    ("come true", "become real", "Unit 6"),
    ("lunch", "midday meal", "Unit 6"),
    ("coffee", "drink from beans", "Unit 6"),
    ("letter", "written symbol", "Unit 6"),
    ("dinner", "evening meal", "Unit 6"),
    ("knife", "tool for cutting", "Unit 6"),
    ("chicken", "bird meat", "Unit 6"),
    ("fork", "tool for eating", "Unit 6"),
    ("butter", "yellow milk fat", "Unit 6"),
    ("spoon", "tool for soup", "Unit 6"),
    ("bread", "baked flour food", "Unit 6"),
    ("cup", "drinking bowl with handle", "Unit 6"),
    ("rice", "grains of food", "Unit 6"),
    ("biscuit", "thin flat cake", "Unit 6"),
    ("dessert", "sweet food after meal", "Unit 6"),
    ("croissant", "curved bread", "Unit 6"),
    ("snack", "small food between meals", "Unit 6"),
    ("frog", "green jumping animal", "Unit 6"),
    ("because", "for the reason that", "Unit 6"),
    ("pizza", "flat bread with toppings", "Unit 6"),
    ("onion", "strong tasting vegetable", "Unit 6"),
    ("also", "in addition", "Unit 6"),
    ("olive", "small green/black fruit", "Unit 6"),
    ("wash", "clean with water", "Unit 6"),
    ("slice", "thin cut piece", "Unit 6"),
    ("pancake", "flat fried cake", "Unit 6"),
    ("fried", "cooked in oil", "Unit 6"),
    ("healthy", "good for health", "Unit 6"),
    ("cook", "prepare food with heat", "Unit 6"),
    ("sauce", "liquid on food", "Unit 6"),
    ("pasta", "Italian noodle food", "Unit 6"),
    ("plate", "dish for food", "Unit 6"),

    # --- Unit 7 ---
    ("beautiful", "very attractive", "Unit 7"),
    ("push", "move by pressing", "Unit 7"),
    ("park", "public land for pleasure", "Unit 7"),
    ("win", "achieve victory", "Unit 7"),
    ("picnic", "meal eaten outside", "Unit 7"),
    ("in front", "in first place", "Unit 7"),
    ("enter", "take part in", "Unit 7"),
    ("race", "speed competition", "Unit 7"),
    ("chase", "run after to catch", "Unit 7"),
    ("trophy", "prize cup", "Unit 7"),
    ("fall off", "stop being attached", "Unit 7"),
    ("think", "use mind", "Unit 7"),
    ("cycling", "riding a bicycle", "Unit 7"),
    ("cross", "go from one side to other", "Unit 7"),
    ("sailing", "traveling in boat", "Unit 7"),
    ("finishing line", "end of race", "Unit 7"),
    ("diving", "swimming underwater", "Unit 7"),
    ("drop", "let fall", "Unit 7"),
    ("leave", "allow to stay", "Unit 7"),
    ("climbing", "going up mountains", "Unit 7"),
    ("riding", "sitting on horse", "Unit 7"),
    ("feel", "experience emotion", "Unit 7"),
    ("different", "not the same", "Unit 7"),
    ("kick", "hit with foot", "Unit 7"),
    ("hard", "with effort", "Unit 7"),
    ("champion", "winner of competition", "Unit 7"),
    ("strong", "powerful", "Unit 7"),
    ("student", "person studying", "Unit 7"),
    ("practice", "do again and again", "Unit 7"),
    ("calm", "relaxed", "Unit 7"),
    ("hour", "60 minutes", "Unit 7"),
    ("boxing", "sport hitting with gloves", "Unit 7"),
    ("train", "prepare for sport", "Unit 7"),
    ("match", "sports competition", "Unit 7"),
    ("trainer", "sports shoe", "Unit 7"),
    ("give up", "stop trying", "Unit 7"),
    ("gymnast", "person doing gymnastics", "Unit 7"),
    ("coach", "sports trainer", "Unit 7"),
    ("boxer", "person who boxes", "Unit 7"),
    ("Junior", "young people sport", "Unit 7"),
    ("fan", "admirer", "Unit 7"),
    ("footballer", "football player", "Unit 7"),
    ("player", "person playing game", "Unit 7"),
    ("team", "group competing together", "Unit 7"),
    ("cyclist", "bike rider", "Unit 7"),

    # --- Unit 8 ---
    ("river", "water flowing to sea", "Unit 8"),
    ("knight", "soldier on horse", "Unit 8"),
    ("hear", "perceive sound", "Unit 8"),
    ("footstep", "sound of walking", "Unit 8"),
    ("stairs", "steps between floors", "Unit 8"),
    ("guard", "protector", "Unit 8"),
    ("careful", "giving attention", "Unit 8"),
    ("flat", "apartment", "Unit 8"),
    ("family", "parents and children", "Unit 8"),
    ("house", "building to live in", "Unit 8"),
    ("ghost", "spirit of dead person", "Unit 8"),
    ("castle", "large fortified building", "Unit 8"),
    ("houseboat", "boat to live on", "Unit 8"),
    ("job", "work or duty", "Unit 8"),
    ("cottage", "small country house", "Unit 8"),
    ("sleep", "rest with eyes closed", "Unit 8"),
    ("check", "look carefully", "Unit 8"),
    ("tower", "tall narrow building", "Unit 8"),
    ("hut", "small simple building", "Unit 8"),
    ("medicine", "treatment for illness", "Unit 8"),
    ("igloo", "snow house", "Unit 8"),
    ("kill", "cause to die", "Unit 8"),
    ("cool", "good or stylish", "Unit 8"),
    ("grass", "green plant on ground", "Unit 8"),
    ("area", "part of place", "Unit 8"),
    ("pilot", "plane flyer", "Unit 8"),
    ("actor", "performer", "Unit 8"),
    ("sick", "ill", "Unit 8"),
    ("dentist", "tooth doctor", "Unit 8"),
    ("hairdresser", "hair cutter", "Unit 8"),
    ("shop assistant", "helper in shop", "Unit 8"),
    ("doctor", "illness treater", "Unit 8"),
    ("firefighter", "fire putter outer", "Unit 8"),
    ("taxi", "car with driver", "Unit 8"),
    ("lake", "water surrounded by land", "Unit 8"),
    ("dinosaur", "ancient large animal", "Unit 8"),
    ("thousands of", "large number", "Unit 8"),
    ("live", "have home", "Unit 8"),
    ("hundreds of", "large amount", "Unit 8"),
    ("capital", "government city", "Unit 8"),
    ("building", "structure with roof", "Unit 8"),
    ("interesting", "special or exciting", "Unit 8"),
    ("tent", "cloth shelter", "Unit 8"),

    # --- Unit 9 ---
    ("camel", "desert animal with humps", "Unit 9"),
    ("sand", "tiny grains of rock", "Unit 9"),
    ("desert", "hot dry land", "Unit 9"),
    ("camp", "stay in tents", "Unit 9"),
    ("pyramid", "Egyptian triangular building", "Unit 9"),
    ("village", "small town", "Unit 9"),
    ("seat", "thing to sit on", "Unit 9"),
    ("thirsty", "needing drink", "Unit 9"),
    ("goat", "animal with horns", "Unit 9"),
    ("sun cream", "skin protection", "Unit 9"),
    ("important", "valuable or necessary", "Unit 9"),
    ("farmer", "person running farm", "Unit 9"),
    ("smoke", "grey gas from fire", "Unit 9"),
    ("fill", "make full", "Unit 9"),
    ("suitcase", "case for clothes", "Unit 9"),
    ("rucksack", "backpack", "Unit 9"),
    ("silk", "smooth cloth", "Unit 9"),
    ("shorts", "short trousers", "Unit 9"),
    ("try", "attempt to do", "Unit 9"),
    ("inventor", "maker of new things", "Unit 9"),
    ("invention", "newly created thing", "Unit 9"),
    ("hot air balloon", "balloon for travel", "Unit 9"),
    ("passenger", "traveler in vehicle", "Unit 9"),
    ("flight", "journey by air", "Unit 9"),
    ("ride", "journey in vehicle", "Unit 9"),
    ("minute", "60 seconds", "Unit 9"),
    ("tie", "attach with string", "Unit 9"),
    ("land", "return to ground", "Unit 9"),
    ("field", "open land", "Unit 9"),
    ("port", "town with harbor", "Unit 9"),
    ("airport", "place for planes", "Unit 9"),
    ("stop", "place bus halts", "Unit 9"),
    ("station", "place train halts", "Unit 9"),
    ("platform", "train boarding area", "Unit 9"),
    ("basket", "container with handle", "Unit 9"),
    ("expensive", "costing much money", "Unit 9"),
    ("cheap", "costing little money", "Unit 9"),
    ("hotel", "place to stay", "Unit 9"),
    ("jeans", "denim pants", "Unit 9"),
    ("visit", "go to see", "Unit 9"),
    ("city centre", "downtown", "Unit 9"),
    ("buy", "get with money", "Unit 9"),

    # --- Unit 10 ---
    ("concert", "music performance", "Unit 10"),
    ("lines", "words for actor", "Unit 10"),
    ("studio", "place to make films", "Unit 10"),
    ("talent", "natural ability", "Unit 10"),
    ("director", "film leader", "Unit 10"),
    ("pretty", "attractive", "Unit 10"),
    ("shoot", "film something", "Unit 10"),
    ("set", "performance place", "Unit 10"),
    ("role", "actor's part", "Unit 10"),
    ("autograph", "famous signature", "Unit 10"),
    ("dressing room", "changing room", "Unit 10"),
    ("act", "perform role", "Unit 10"),
    ("pop group", "music band", "Unit 10"),
    ("cartoon", "drawn film", "Unit 10"),
    ("interview", "asking questions", "Unit 10"),
    ("poor", "having little money", "Unit 10"),
    ("audience", "watchers", "Unit 10"),
    ("neighbor", "person living near", "Unit 10"),
    ("stage", "performance area", "Unit 10"),
    ("company", "business", "Unit 10"),
    ("world", "earth and people", "Unit 10"),
    ("garage", "place for cars", "Unit 10"),
    ("record", "stored info", "Unit 10"),
    ("dwarf", "small imaginary man", "Unit 10"),
    ("dream", "wish", "Unit 10"),
    ("science fiction", "future stories", "Unit 10"),
    ("adventure", "exciting experience", "Unit 10"),
    ("star", "famous person", "Unit 10"),
    ("cameraman", "camera operator", "Unit 10"),
    ("normal", "usual", "Unit 10"),
    ("comedy", "funny show", "Unit 10"),
    ("then", "at that time", "Unit 10"),
    ("drama", "serious play", "Unit 10"),
    ("musical", "play with songs", "Unit 10"),
    ("audition", "performance test", "Unit 10"),
    ("nervous", "worried", "Unit 10"),
    ("marry", "become husband/wife", "Unit 10"),
    ("handsome", "attractive man", "Unit 10"),
    ("relax", "become calm", "Unit 10"),
    ("prince", "king's son", "Unit 10"),
    ("lucky", "having good luck", "Unit 10"),
    ("princess", "king's daughter", "Unit 10"),

    # --- Unit 11 (NEW) ---
    ("map", "drawing showing countries/roads", "Unit 11"),
    ("butterfly", "flying insect with bright wings", "Unit 11"),
    ("path", "track for walking", "Unit 11"),
    ("cave", "hole in hill or ground", "Unit 11"),
    ("dangerous", "likely to harm", "Unit 11"),
    ("dolphin", "intelligent sea animal", "Unit 11"),
    ("horrible", "very unpleasant", "Unit 11"),
    ("eagle", "bird with good eyesight", "Unit 11"),
    ("bat", "mouse-like animal with wings", "Unit 11"),
    ("leopard", "spotted cat", "Unit 11"),
    ("swan", "white bird with long neck", "Unit 11"),
    ("president", "leader of government", "Unit 11"),
    ("whale", "very large sea animal", "Unit 11"),
    ("worm", "animal with long thin body", "Unit 11"),
    ("unusual", "not normal", "Unit 11"),
    ("lift", "machine carrying people up", "Unit 11"),
    ("torch", "hand-held light", "Unit 11"),
    ("binoculars", "equipment to see far", "Unit 11"),
    ("bedroom", "room for sleeping", "Unit 11"),
    ("insect", "small animal with six legs", "Unit 11"),
    ("snake", "long animal with no legs", "Unit 11"),
    ("pony", "small horse", "Unit 11"),
    ("puppy", "young dog", "Unit 11"),
    ("sculpture", "art made of stone/wood", "Unit 11"),
    ("elephant", "large grey animal", "Unit 11"),
    ("cow", "farm animal for milk", "Unit 11"),
    ("word", "letters that mean something", "Unit 11"),
    ("goldfish", "small orange pet fish", "Unit 11"),
    ("kitten", "young cat", "Unit 11"),
    ("at first", "in the beginning", "Unit 11"),
    ("parrot", "bird that copies speech", "Unit 11"),
    ("person", "human being", "Unit 11"),
    ("lizard", "small animal with tail", "Unit 11"),
    ("naughty", "behaving badly", "Unit 11"),
    ("neighbourhood", "area near a place", "Unit 11"),
    ("lose", "not able to find", "Unit 11"),
    ("metre", "100 centimetres", "Unit 11"),
    ("all", "completely", "Unit 11"),
    ("find", "discover something", "Unit 11"),
    ("count", "say numbers in order", "Unit 11"),

    # --- Unit 12 (NEW) ---
    ("switch on", "turn light on", "Unit 12"),
    ("medallion", "jewellery coin on chain", "Unit 12"),
    ("raincoat", "coat for rain", "Unit 12"),
    ("gold", "bright yellow color", "Unit 12"),
    ("anymore", "any longer", "Unit 12"),
    ("rainbow", "colors in sky", "Unit 12"),
    ("rock", "large piece of stone", "Unit 12"),
    ("rainy", "having a lot of rain", "Unit 12"),
    ("sunny", "bright light from sun", "Unit 12"),
    ("cloudy", "many clouds", "Unit 12"),
    ("snowy", "covered with snow", "Unit 12"),
    ("windy", "having a lot of wind", "Unit 12"),
    ("look for", "search for", "Unit 12"),
    ("foggy", "not clear", "Unit 12"),
    ("journey", "traveling from place to place", "Unit 12"),
    ("kilometre", "1000 metres", "Unit 12"),
    ("plant", "living thing in soil", "Unit 12"),
    ("survive", "continue to live", "Unit 12"),
    ("destroy", "damage badly", "Unit 12"),
    ("sell", "give for money", "Unit 12"),
    ("arrive", "get to a place", "Unit 12"),
    ("canyon", "deep valley", "Unit 12"),
    ("cliff", "high steep rocks", "Unit 12"),
    ("forest", "area of trees", "Unit 12"),
    ("mountain", "very high land", "Unit 12"),
    ("ocean", "large sea area", "Unit 12"),
    ("waterfall", "water flowing from high", "Unit 12"),
    ("cut down", "make fall by cutting", "Unit 12"),
    ("rainforest", "forest with much rain", "Unit 12"),
    ("wild", "in natural state", "Unit 12"),
    ("tornado", "dangerous turning wind", "Unit 12"),
    ("wind", "movement of air", "Unit 12"),
    ("cloud", "water in sky", "Unit 12"),
    ("lift", "put higher", "Unit 12"),
    ("towards", "in direction of", "Unit 12"),
    ("suddenly", "quickly unexpected", "Unit 12"),
    ("spring", "season after winter", "Unit 12"),
    ("drive", "make car go", "Unit 12"),
    ("run away", "escape", "Unit 12"),
    ("careful", "attention to avoid mistake", "Unit 12"),
    ("follow", "go behind", "Unit 12"),
    ("probably", "likely to happen", "Unit 12"),
]

def reset_and_import():
    # 1. 暴力重置：如果数据库文件存在，直接删除，保证 ID 从 1 开始
    if os.path.exists(DB_NAME):
        try:
            os.remove(DB_NAME)
            print(f"🗑️  旧数据库 {DB_NAME} 已删除，准备重新创建...")
        except Exception as e:
            print(f"⚠️ 无法删除旧数据库: {e}")
    
    # 2. 初始化新库
    init_db()
    
    # 3. 导入全部数据
    print(f"📦 正在导入 {len(full_vocabulary_data)} 个单词...")
    add_words_bulk(full_vocabulary_data)
    
    # 4. 验证
    total, new_words = get_stats()
    print("=" * 40)
    print(f"✅ 全部导入完成！")
    print(f"📚 总单词量: {total}")
    print(f"🆕 待学新词: {new_words}")
    print(f"🔢 自动分组: 共 {(total // 20) + 1} 组")
    print("=" * 40)

if __name__ == "__main__":
    reset_and_import()